



build: clean all

clean:
	@echo '*********正在开始清理*************'
	cd x86 && $(MAKE) clean
	@echo '*********正在清理结束*************'

X86BARD = -f ./Makefile

all:
	@echo '*********正在开始编译构建系统*************'
	cd x86 && $(MAKE) $(X86BARD)
	@echo '*********正在编译构建系统结束*************'
